import assert from 'node:assert/strict';
import { createProject, addPrimarySource, addSuppliedStem, attachRecoveredPart, assignRenderer, buildReassemblyManifest, validateProject } from '../src/core/project.js';
const project=createProject({name:'Gate',sourceKind:'full_mix',createdAt:'2026-09-25T00:00:00.000Z'});
const source=addPrimarySource(project,{fileName:'master.wav',durationSec:2,sampleRate:48000,channels:2});
const supplied=addSuppliedStem(project,{fileName:'fiddle.wav',durationSec:2,sampleRate:48000,channels:1},{instrument:'fiddle'});
const recovered=attachRecoveredPart(project,{instrument:'fiddle',sourceAssetId:supplied.sourceAssetId,performance:{schema:'fidelis.performance.v0.1',performance:[{start:0,duration:1,note:'A4'}],pitchContour:[]}});
assignRenderer(project,recovered.id,{adapterId:'instrudio'});
buildReassemblyManifest(project);
assert.ok(source.id); assert.equal(project.parts.length,2); assert.equal(validateProject(project).valid,true);
console.log('FIDELIS FRONTEND PROJECT MODEL: PASS');
